#! /usr/bin/env python

srvurl = '127.0.0.1:5678'
srvpasswd = 'password'

# Weapons, construction items resources atire tool medical food ammunition traps misc
items = {
"weapons": {"Eoka Pistol": "pistol.eoka",
"Revolver": "pistol.revolver",
"Semi-Automatic Pistol": "pistol.semiauto",
"Bone Club": "bone.club",
"Hunting Bow": "bow.hunting",
"Crossbow": "crossbow",
"Mace": "mace",
"Machete": "machete",
"M249": "lmg.m249",
"Bone Knife": "knife.bone",
"Longsword": "longsword",
"Assault Rifle": "rifle.ak",
"Bolt Action Rifle": "rifle.bolt",
"Semi-Automatic Rifle": "rifle.semiauto",
"Pump Shotgun": "shotgun.pump",
"Waterpipe Shotgun": "shotgun.waterpipe",
"Custom SMG": "smg.2",
"Thompson": "smg.thompson",
"Stone Spear": "spear.stone",
"Wooden Spear": "spear.wooden",
"Weapon Flashlight": "weapon.mod.flashlight",
"Holosight": "weapon.mod.holosight",
"Weapon Lasersight": "weapon.mod.lasersight",
"Silencer": "weapon.mod.silencer",
"4x Zoom Scope": "weapon.mod.small.scope",
"Rocket Launcher": "rocket.launcher",
"Salvaged Cleaver": "salvaged.cleaver",
"Salvaged Sword": "salvaged.sword",
"Beancan Grenade": "grenade.beancan",
"F1 Grenade": "grenade.f1"},
"construction": {"Tool Cupboard": "cupboard.tool",
"Sheet Metal Double Door": "door.double.hinged.metal",
"Armored Double Door": "door.double.hinged.toptier",
"Wood Double Door": "door.double.hinged.wood",
"Sheet Metal Door": "door.hinged.metal",
"Armored Door": "door.hinged.toptier",
"Wooden Door": "door.hinged.wood",
"Building Plan": "building.planner",
"Door Key": "door.key",
"A floor grill": "floor.grill",
"Ladder Hatch": "floor.ladder.hatch",
"High External Stone Gate": "gates.external.high.stone",
"High External Wooden Gate": "gates.external.high.wood",
"Wind Turbine": "generator.wind.scrap",
"Wooden Ladder": "ladder.wooden.wall",
"Code Lock": "lock.code",
"Lock": "lock.key",
"Pump Jack": "mining.pumpjack",
"Mining Quarry": "mining.quarry",
"High External Wooden Wall": "wall.external.high",
"High External Stone Wall": "wall.external.high.stone",
"Prison Cell Wall": "wall.frame.cell",
"Prison Cell Gate": "wall.frame.cell.gate",
"Chainlink Fence": "wall.frame.fence",
"Chainlink Fence Gate": "wall.frame.fence.gate",
"Shop Front": "wall.frame.shopfront",
"Metal Window Bars": "wall.window.bars.metal",
"Reinforced Window Bars": "wall.window.bars.toptier",
"Wooden Window Bars": "wall.window.bars.wood",
"Large Water Catcher": "water.catcher.large",
"Small Water Catcher": "water.catcher.small",
"Metal horizontal embrasure": "shutter.metal.embrasure.a",
"Metal Vertical embrasure": "shutter.metal.embrasure.b",
"Wood Shutters": "shutter.wood.a"},
"items": {"Concrete Barricade": "barricade.concrete",
"Metal Barricade": "barricade.metal",
"Sandbag Barricade": "barricade.sandbags",
"Stone Barricade": "barricade.stone",
"Wooden Barricade": "barricade.wood",
"Barbed Wooden Barricade": "barricade.woodwire",
"Bed": "bed",
"Repair Bench": "box.repair.bench",
"Wood Storage Box": "box.wooden",
"Large Wood Box": "box.wooden.large",
"Camp Fire": "campfire",
"Furnace": "furnace",
"Large Furnace": "furnace.large",
"Jack O Lantern Angry": "jackolantern.angry",
"Jack O Lantern Happy": "jackolantern.happy",
"Lantern": "lantern",
"Pookie Bear": "pookie.bear",
"Research Table": "research.table",
"Road Sign Jacket": "roadsign.jacket",
"Road Sign Kilt": "roadsign.kilt",
"Salvaged Shelves": "shelves",
"Two Sided Hanging Sign": "sign.hanging",
"Large Banner Hanging": "sign.hanging.banner.large",
"Two Sided Ornate Hanging Sign": "sign.hanging.ornate",
"Landscape Picture Frame": "sign.pictureframe.landscape",
"Portrait Picture Frame": "sign.pictureframe.portrait",
"Tall Picture Frame": "sign.pictureframe.tall",
"XL Picture Frame": "sign.pictureframe.xl",
"XXL Picture Frame": "sign.pictureframe.xxl",
"Large Banner on pole": "sign.pole.banner.large",
"Double Sign Post": "sign.post.double",
"Single Sign Post": "sign.post.single",
"One Sided Town Sign Post": "sign.post.town",
"Two Sided Town Sign Post": "sign.post.town.roof",
"Huge Wooden Sign": "sign.wooden.huge",
"Large Wooden Sign": "sign.wooden.large",
"Wooden Sign": "sign.wooden.medium",
"Small Wooden Sign": "sign.wooden.small",
"Sleeping Bag": "sleepingbag",
"Small Oil Refinery": "small.oil.refinery",
"Reactive Target": "target.reactive",
"Small Stash": "stash.small",
"SUPER Stocking": "stocking.large",
"Small Stocking": "stocking.small"},
"resources": {"High Quality Metal Ore": "hq.metal.ore",
"Low Grade Fuel": "lowgradefuel",
"Metal Fragments": "metal.fragments",
"Metal Ore": "metal.ore",
"Stones": "stones",
"Sulfur": "sulfur",
"Sulfur Ore": "sulfur.ore",
"High Quality Metal": "metal.refined",
"Bone Fragments": "bone.fragments",
"CCTV Camera": "cctv.camera",
"Charcoal": "charcoal",
"Cloth": "cloth",
"Coal": "coal",
"Crude Oil": "crude.oil",
"Animal Fat": "fat.animal",
"Leather": "leather",
"Paper Map": "map",
"Paper": "paper",
"Battery - Small": "battery.small",
"Human Skull": "skull.human",
"Wolf Skull": "skull.wolf",
"Water": "water",
"Wood": "wood",
"Targeting Computer": "targeting.computer",
"Gun Powder": "gunpowder"},
"atire": {"Hide Pants": "attire.hide.pants",
"Hide Poncho": "attire.hide.poncho",
"Hide Vest": "attire.hide.vest",
"Bone Jacket": "bone.armor.jacket",
"Bone Armor Pants": "bone.armor.pants",
"Bota Bag": "botabag",
"Bucket Helmet": "bucket.helmet",
"Leather Gloves": "burlap.gloves",
"Burlap Headwrap": "burlap.headwrap",
"Burlap Shirt": "burlap.shirt",
"Burlap Shoes": "burlap.shoes",
"Burlap Trousers": "burlap.trousers",
"Beenie Hat": "hat.beenie",
"Boonie Hat": "hat.boonie",
"Candle Hat": "hat.candle",
"Baseball Cap": "hat.cap",
"Miners Hat": "hat.miner",
"Wolf Headdress": "hat.wolf",
"Hazmat Boots": "hazmat.boots",
"Hazmat Gloves": "hazmat.gloves",
"Hazmat Helmet": "hazmat.helmet",
"Hazmat Jacket": "hazmat.jacket",
"Hazmat Pants": "hazmat.pants",
"Hoodie": "hoodie",
"Jacket": "jacket",
"Snow Jacket - Red": "jacket.snow",
"Bandana Mask": "mask.bandana",
"Metal Facemask": "metal.facemask",
"Metal Chest Plate": "metal.plate.torso",
"Riot Helmet": "riot.helmet",
"Santa Hat": "santahat",
"Boots": "shoes.boots",
"T-Shirt": "tshirt",
"Longsleeve T-Shirt": "tshirt.long",
"Coffee Can Helmet": "coffeecan.helmet",
"Pants": "pants",
"Wood Chestplate": "wood.armor.jacket",
"Wood Armor Pants": "wood.armor.pants",
"Large Present": "xmas.present.large",
"Medium Present": "xmas.present.medium",
"Small Present": "xmas.present.small"},
"tool": {"Salvaged Axe": "axe.salvaged",
"Hammer": "hammer",
"Salvaged Hammer": "hammer.salvaged",
"Hatchet": "hatchet",
"Salvaged Icepick": "icepick.salvaged",
"Stone Pick Axe": "stone.pickaxe",
"Stone Hatchet": "stonehatchet",
"Supply Signal": "supply.signal",
"Survey Charge": "surveycharge",
"Torch": "torch",
"Camera": "tool.camera",
"Flare": "flare",
"Timed Explosive Charge": "explosive.timed",
"Explosives": "explosives",
"Pick Axe": "pickaxe",
"Rock": "rock"},
"medical": {"Anti-Radiation Pills": "antiradpills",
"Bandage": "bandage",
"Blood": "blood",
"Large Medkit": "largemedkit",
"Medical Syringe": "syringe.medical"},
"food": {"Apple": "apple",
"Rotten Apple": "apple.spoiled",
"Bear Meat": "bearmeat",
"Burnt Bear Meat": "bearmeat.burned",
"Bear Meat Cooked": "bearmeat.cooked",
"Black Raspberries": "black.raspberries",
"Blueberries": "blueberries",
"Can of Beans": "can.beans",
"Empty Can Of Beans": "can.beans.empty",
"Can of Tuna": "can.tuna",
"Empty Tuna Can": "can.tuna.empty",
"Candy Cane": "candycane",
"Burned Chicken": "chicken.burned",
"Cooked Chicken.": "chicken.cooked",
"Raw Chicken Breast": "chicken.raw",
"Spoiled Chicken": "chicken.spoiled",
"Chocolate Bar": "chocholate",
"Corn": "corn",
"Granola Bar": "granolabar",
"Burned Human Meat": "humanmeat.burned",
"Cooked Human Meat": "humanmeat.cooked",
"Raw Human Meat": "humanmeat.raw",
"Spoiled Human Meat": "humanmeat.spoiled",
"Pork": "meat.boar",
"Burned Pork": "meat.pork.burned",
"Cooked Pork": "meat.pork.cooked",
"Burned Wolf Meat": "wolfmeat.burned",
"Cooked Wolf Meat": "wolfmeat.cooked",
"Raw Wolf Meat": "wolfmeat.raw",
"Spoiled Wolf Meat": "wolfmeat.spoiled",
"Pumpkin": "pumpkin",
"Mushroom": "mushroom",
"Corn Seed": "seed.corn",
"Pumpkin Seed": "seed.pumpkin",
"Small Water Bottle": "smallwaterbottle"},
"ammunition": {"Handmade Shell": "ammo.handmade.shell",
"Pistol Bullet": "ammo.pistol",
"Incendiary Pistol Bullet": "ammo.pistol.fire",
"HV Pistol Ammo": "ammo.pistol.hv",
"5.56 Rifle Ammo": "ammo.rifle",
"Explosive 5.56 Rifle Ammo": "ammo.rifle.explosive",
"HV 5.56 Rifle Ammo": "ammo.rifle.hv",
"Incendiary 5.56 Rifle Ammo": "ammo.rifle.incendiary",
"Rocket": "ammo.rocket.basic",
"Incendiary Rocket": "ammo.rocket.fire",
"High Velocity Rocket": "ammo.rocket.hv",
"Smoke Rocket WIP!!!!": "ammo.rocket.smoke",
"12 Gauge Buckshot": "ammo.shotgun",
"12 Gauge Slug": "ammo.shotgun.slug",
"High Velocity Arrow": "arrow.hv",
"Wooden Arrow": "arrow.wooden"},
"trap": {"Hide Boots": "attire.hide.boots",
"Auto Turret": "autoturret",
"Snap Trap": "trap.bear",
"Land Mine": "trap.landmine",
"Wooden Floor Spikes": "spikes.floor"},
"misc": {"Acoustic Guitar": "fun.guitar",
"Blueprint Book": "blueprint_book",
"Blueprint Fragment": "blueprint_fragment",
"Blueprint Library": "blueprint_library",
"Blueprint Page": "blueprint_page",
"Note": "note"}
}


def contentcode():
    code = ''
    count = 1
    for key in items.keys():
        code += '<input type="radio"id="radioButton%s"name="radioButton"value="%s"/>%s' % (count, key, key)
        count += 1

    for key in items.keys():
        code += '<select name="%s"id="%s"style="display: none">' % (key, key)
        code += '    <option selected="selected"value="None">Choose %s</option>' % key
        for nitem in items[key]:
            code += '<option value="%s">%s</option>' % (items[key][nitem], nitem)
        code += '</select>'

    return code
